AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bingsuDonationTrans

  Sample SAM Template for bingsuDonationTrans


Globals:
  Function:
    Timeout: 3
    Runtime: python3.8
    Environment:
      Variables:
        BINGSU_DONATION_TRANS_TABLE_NAME: !Ref DonationTransTable
        BINGSU_TOTAL_SUM_TABLE_NAME: !Ref TotalSumTable
        BINGSU_TOTAL_CO2_TABLE_NAME: !Ref TotalCo2Table

Resources:
  AddDonationTransFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: bingsuDonationTrans/
      Handler: app.add_donation_trans
    
  GetTotalSumTransFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: bingsuDonationTrans/
      Handler: app.get_total_sum
      
  GetCo2AmountByCompanyFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: bingsuDonationTrans/
      Handler: app.get_total_co2_amount_by_company
      
  UpdateTotalCo2AmountFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: bingsuDonationTrans/
      Handler: app.update_total_co2_amount

  GetDonationTransByUserId:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: bingsuDonationTrans/
      Handler: app.get_donation_trans_by_user_id
      
  DonationTransTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: transaction_id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: transaction_id
          KeyType: HASH
      TableName: "BingsuDonationTrans"
      
  TotalSumTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: transaction_id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: transaction_id
          KeyType: HASH
      TableName: "BingsuTotalSum"
      
  TotalCo2Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: date
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: date
          KeyType: HASH
      TableName: "BingsuTotalCo2"
      

Outputs:
  AddDonationTransFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt AddDonationTransFunction.Arn
  AddDonationTransFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt AddDonationTransFunctionRole.Arn
