AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bingsuDonationTrans

  Sample SAM Template for bingsuDonationTrans


Globals:
  Function:
    Timeout: 3
    Runtime: python3.8

Resources:
  TestFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      
  DonationTransTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: transaction_id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: transaction_id
          KeyType: HASH
      TableName: "BingsuDonationTrans"
      

Outputs:
  TestFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt TestFunction.Arn
  TestFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt TestFunctionRole.Arn
